minor patches

diff --git a/inou/yosys/lgcheck b/inou/yosys/lgcheck
--- a/inou/yosys/lgcheck
+++ b/inou/yosys/lgcheck
@@ -1,9 +1,10 @@
 #!/bin/bash
 
-TEMP=$(getopt -o r::,i:: --long reference::,implementation:: -n 'yosys.sh' -- "$@")
+TEMP=$(getopt -o r::,i::,l:: --long reference::,implementation::,--cell_library:: -n 'lgcheck' -- "$@")
 eval set -- "$TEMP"
 
 YOSYS=./subs/yosys/bin/yosys
+CELLLIB=""
 while true ; do
     case "$1" in
         -r|--reference)
@@ -15,6 +16,11 @@ while true ; do
           case "$2" in
               "") shift 2 ;;
               *) GATE=$2 ; shift 2 ;;
+          esac ;;
+        -l|--cell_library)
+          case "$2" in
+              "") shift 2 ;;
+              *) CELLLIB=$2 ; shift 2 ;;
           esac ;;
         --)
           shift
@@ -52,9 +58,17 @@ if [ ! -f ${YOSYS} ]; then
   exit 1
 fi
 
+if [ "${CELLLIB}" != "" ]; then
+  if [ ! -f ${CELLLIB} ]; then
+    echo "cell library ${CELLLIB} not found"
+    exit 1
+  fi
+  lib="read_verilog ${CELLLIB}"
+fi
+
 yosys_read="read_verilog -sv ${GOLD}; proc; hierarchy -auto-top; flatten; rename -top gold; design -stash gold;
             read_verilog -sv ${GATE}; proc; hierarchy -auto-top; flatten; rename -top gate; design -stash gate;
-            design -copy-from gold -as gold gold; design -copy-from gate -as gate gate"
+            design -copy-from gold -as gold gold; design -copy-from gate -as gate gate; ${lib};"
 
 yosys_prep="equiv_make gold gate equiv; prep -flatten -top equiv; hierarchy -top equiv; hierarchy -check; flatten; proc; opt_clean;"
 
