fm first

diff --git a/inou/yosys/lgcheck b/inou/yosys/lgcheck
--- a/inou/yosys/lgcheck
+++ b/inou/yosys/lgcheck
@@ -112,6 +112,55 @@ if [ ! -f "${YOSYS}" ]; then
   fi
 fi
 
+fm_top=$OPT_TOP
+if [ "${fm_top}" == "" ]; then
+  filename=$(basename -- "$GATE")
+  fm_top="${filename%.*}"
+  if [[ $fm_top =~ "long_" ]]; then
+    fm_top=${fm_top:5}
+  elif [[ $fm_top =~ "fixme_" ]]; then
+    fm_top=${fm_top:6}
+  fi
+fi
+
+if [ -z $FM_SHELL ]; then
+  FM_SHELL=`which fm_shell`
+  if [ $? -ne 0 ]; then
+    echo "fm_shell not found, make sure fm_shell is in your path, or define the FM_SHELL environment variable"
+    exit 1
+  fi
+fi
+
+if [ -x ${FM_SHELL} ]; then
+  echo "using formality"
+
+  echo "
+  set_app_var synopsys_auto_setup true
+  set_app_var hdlin_ignore_parallel_case false
+  set_app_var hdlin_ignore_full_case false
+  read_sverilog -r  \"${GOLD}\"
+  set_top ${fm_top}
+  read_sverilog -i  \"${GATE}\"
+  set_top ${fm_top}
+  match
+  report_unmatched_points >> \"fm_${fm_top}_error.log\"
+  if { ![verify] }  {
+    report_failing_points >> \"fm_${fm_top}_error.log\"
+    report_aborted >> \"fm_${fm_top}_error.log\"
+    analyze_points -all >> \"fm_${fm_top}_error.log\"
+  }
+  exit
+  " > fm_script_${fm_top}.tcl
+
+  ${FM_SHELL} -64bit -f fm_script_${fm_top}.tcl | grep "Verification SUCCEEDED"
+  if [ $? -eq 0 ]; then
+    echo "5.Successfully matched ${GATE} with ${GOLD} top:${fm_top}"
+    exit 0
+  fi
+
+  echo "WARN: formality failed to prove equivalency."
+fi
+
 echo "using yosys:"${YOSYS}
 
 if [ ! -f ${YOSYS} ]; then
@@ -180,7 +229,7 @@ ${YOSYS} -p " read_verilog -sv ${GOLD}; hierarchy ${TOP_STR}; opt; flatten ; ren
 
               miter -equiv -flatten -make_outputs -ignore_gold_x gold gate miter
               hierarchy -top miter
-              sat -tempinduct -prove trigger 0 -set-init-undef -enable_undef -set-def-inputs -ignore_unknown_cells -show-ports miter -timeout 60
+              sat -tempinduct -prove trigger 0 -set-init-undef -enable_undef -set-def-inputs -ignore_unknown_cells -show-ports miter
               " \
     2> /dev/null | tee lgcheck2.log | grep "proven: SUCC"
 if [ $? -eq 0 ]; then
@@ -209,54 +258,7 @@ if [ $? -eq 0 ]; then
   exit 0
 fi
 
-echo "WARN: Yosys failed to prove equivalency, trying to prove equivalency with Formality."
-
-fm_top=$OPT_TOP
-if [ "${fm_top}" == "" ]; then
-  filename=$(basename -- "$GATE")
-  fm_top="${filename%.*}"
-  if [[ $fm_top =~ "long_" ]]; then
-    fm_top=${fm_top:5}
-  elif [[ $fm_top =~ "fixme_" ]]; then
-    fm_top=${fm_top:6}
-  fi
-fi
-
-if [ -z $FM_SHELL ]; then
-  FM_SHELL=`which fm_shell`
-  if [ $? -ne 0 ]; then
-    echo "fm_shell not found, make sure fm_shell is in your path, or define the FM_SHELL environment variable"
-    exit 1
-  fi
-fi
-
-if [ ! -f ${FM_SHELL} ]; then
-  echo "fm_shell not found, make sure fm_shell is in your path"
-  exit 1
-fi
-
-echo "
-    set_app_var synopsys_auto_setup true
-    set_app_var hdlin_ignore_parallel_case false
-    set_app_var hdlin_ignore_full_case false
-    read_sverilog -r  \"${GOLD}\"
-    set_top ${fm_top}
-    read_sverilog -i  \"${GATE}\"
-    set_top ${fm_top}
-    match
-    report_unmatched_points >> \"fm_${fm_top}_error.log\"
-    if { ![verify] }  {
-      report_failing_points >> \"fm_${fm_top}_error.log\"
-        report_aborted >> \"fm_${fm_top}_error.log\"
-        analyze_points -all >> \"fm_${fm_top}_error.log\"
-    }
-exit" > fm_script_${fm_top}.tcl
-
-${FM_SHELL} -64bit -f fm_script_${fm_top}.tcl | grep "Verification SUCCEEDED"
-if [ $? -eq 0 ]; then
-  echo "5.Successfully matched ${GATE} with ${GOLD} top:${fm_top}"
-  exit 0
-fi
+echo "WARN: Yosys failed to prove equivalency."
 
 echo "FAIL: circuits are not equivalent ${GATE} vs ${GOLD} with top:${fm_top}"
 exit 1
